# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := FlasherTest
ARDUINO_LIBS := AUnit AceCommon AXP202X_Library
ARDUINO_LIB_DIRS := ${ARDUINO_LIBRARIES}
include ${ARDUINO_LIBRARIES}/EpoxyDuino/EpoxyDuino.mk
